spring:
  application:
    name: eurekaserverapp
  security:
    basic:
      enable: true
    user:
      name: microservice-eureka
      password: rv-meeaocrireecsuki

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}