spring:
  application:
    name: eurekaserverapp
  security:
    basic:
      enable: true
    user:
      name: microservice-eureka
      password: rv-meeaocrireecsuki

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
